version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      DEBUG: 1
      SECRET_KEY: django-insecure-p@(dtf2yao31az73o@hj)y*_#@#r!6+vsef%vvin*t*mlc+vh!
      DB_HOST: db
      DB_NAME: db_tarefas
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
    volumes:
      - .:/home/app/api

  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: db
      POSTGRES_DB: db_tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/home/app/api
    environment:
      DEBUG: 0
      SECRET_KEY: django-insecure-p@(dtf2yao31az73o@hj)y*_#@#r!6+vsef%vvin*t*mlc+vh!
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DB_HOST: db
      DB_NAME: db_tarefas
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - rabbitmq
      - backend

  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/home/app/api
    environment:
      DEBUG: 0
      SECRET_KEY: django-insecure-p@(dtf2yao31az73o@hj)y*_#@#r!6+vsef%vvin*t*mlc+vh!
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DB_HOST: db
      DB_NAME: db_tarefas
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - rabbitmq
      - backend

volumes:
  db:
    driver: local